"""Añadir campos de direccion

Revision ID: b7f24a178e19
Revises: d045c81ac0dd
Create Date: 2025-12-12 12:40:43.834111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f24a178e19'
down_revision = 'd045c81ac0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domicilio', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('localidad', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cp', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('provincia', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))

    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calle', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('localidad', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cp', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('provincia', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajador', schema=None) as batch_op:
        batch_op.drop_column('provincia')
        batch_op.drop_column('cp')
        batch_op.drop_column('localidad')
        batch_op.drop_column('calle')

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('telefono')
        batch_op.drop_column('email')
        batch_op.drop_column('provincia')
        batch_op.drop_column('cp')
        batch_op.drop_column('localidad')
        batch_op.drop_column('domicilio')

    # ### end Alembic commands ###
