"""Migracion inicial estructura diagrama

Revision ID: d045c81ac0dd
Revises: 
Create Date: 2025-12-12 10:58:05.850223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd045c81ac0dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nombrecomercial', sa.String(length=255), nullable=True),
    sa.Column('cif', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_empresa')
    )
    op.create_table('horario',
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('nombre_horario', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('franjas',
    sa.Column('id_dia', sa.Integer(), nullable=False),
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('hora_entrada', sa.String(length=10), nullable=True),
    sa.Column('hora_salida', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id_dia'], ['dia.id'], ),
    sa.ForeignKeyConstraint(['id_horario'], ['horario.id_horario'], ),
    sa.PrimaryKeyConstraint('id_dia', 'id_horario')
    )
    op.create_table('trabajador',
    sa.Column('id_trabajador', sa.Integer(), nullable=False),
    sa.Column('nif', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('passw', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telef', sa.String(length=20), nullable=True),
    sa.Column('idEmpresa', sa.Integer(), nullable=True),
    sa.Column('idHorario', sa.Integer(), nullable=True),
    sa.Column('idRol', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idEmpresa'], ['empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['idHorario'], ['horario.id_horario'], ),
    sa.ForeignKeyConstraint(['idRol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_trabajador')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabajador')
    op.drop_table('franjas')
    op.drop_table('rol')
    op.drop_table('horario')
    op.drop_table('empresa')
    op.drop_table('dia')
    # ### end Alembic commands ###
